/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InquiriesRouteImport } from './routes/inquiries'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostNewRouteImport } from './routes/post.new'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as InquiriesThreadIdRouteImport } from './routes/inquiries.$threadId'
import { Route as GalleryPostIdRouteImport } from './routes/gallery.$postId'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'
import { Route as AssignmentsCourseIdRouteImport } from './routes/assignments.$courseId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesRoute = InquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostNewRoute = PostNewRouteImport.update({
  id: '/post/new',
  path: '/post/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesThreadIdRoute = InquiriesThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => InquiriesRoute,
} as any)
const GalleryPostIdRoute = GalleryPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => GalleryRoute,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsCourseIdRoute = AssignmentsCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AssignmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/inquiries': typeof InquiriesRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/assignments/$courseId': typeof AssignmentsCourseIdRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/gallery/$postId': typeof GalleryPostIdRoute
  '/inquiries/$threadId': typeof InquiriesThreadIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/post/new': typeof PostNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/inquiries': typeof InquiriesRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/assignments/$courseId': typeof AssignmentsCourseIdRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/gallery/$postId': typeof GalleryPostIdRoute
  '/inquiries/$threadId': typeof InquiriesThreadIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/post/new': typeof PostNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/inquiries': typeof InquiriesRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/assignments/$courseId': typeof AssignmentsCourseIdRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/gallery/$postId': typeof GalleryPostIdRoute
  '/inquiries/$threadId': typeof InquiriesThreadIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/post/new': typeof PostNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assignments'
    | '/dashboard'
    | '/forgot-password'
    | '/gallery'
    | '/inquiries'
    | '/library'
    | '/login'
    | '/notices'
    | '/profile'
    | '/signup'
    | '/assignments/$courseId'
    | '/course/$courseId'
    | '/gallery/$postId'
    | '/inquiries/$threadId'
    | '/post/$postId'
    | '/post/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assignments'
    | '/dashboard'
    | '/forgot-password'
    | '/gallery'
    | '/inquiries'
    | '/library'
    | '/login'
    | '/notices'
    | '/profile'
    | '/signup'
    | '/assignments/$courseId'
    | '/course/$courseId'
    | '/gallery/$postId'
    | '/inquiries/$threadId'
    | '/post/$postId'
    | '/post/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assignments'
    | '/dashboard'
    | '/forgot-password'
    | '/gallery'
    | '/inquiries'
    | '/library'
    | '/login'
    | '/notices'
    | '/profile'
    | '/signup'
    | '/assignments/$courseId'
    | '/course/$courseId'
    | '/gallery/$postId'
    | '/inquiries/$threadId'
    | '/post/$postId'
    | '/post/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssignmentsRoute: typeof AssignmentsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRouteWithChildren
  InquiriesRoute: typeof InquiriesRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  NoticesRoute: typeof NoticesRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
  PostPostIdRoute: typeof PostPostIdRoute
  PostNewRoute: typeof PostNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries': {
      id: '/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof InquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/new': {
      id: '/post/new'
      path: '/post/new'
      fullPath: '/post/new'
      preLoaderRoute: typeof PostNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries/$threadId': {
      id: '/inquiries/$threadId'
      path: '/$threadId'
      fullPath: '/inquiries/$threadId'
      preLoaderRoute: typeof InquiriesThreadIdRouteImport
      parentRoute: typeof InquiriesRoute
    }
    '/gallery/$postId': {
      id: '/gallery/$postId'
      path: '/$postId'
      fullPath: '/gallery/$postId'
      preLoaderRoute: typeof GalleryPostIdRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/$courseId': {
      id: '/assignments/$courseId'
      path: '/$courseId'
      fullPath: '/assignments/$courseId'
      preLoaderRoute: typeof AssignmentsCourseIdRouteImport
      parentRoute: typeof AssignmentsRoute
    }
  }
}

interface AssignmentsRouteChildren {
  AssignmentsCourseIdRoute: typeof AssignmentsCourseIdRoute
}

const AssignmentsRouteChildren: AssignmentsRouteChildren = {
  AssignmentsCourseIdRoute: AssignmentsCourseIdRoute,
}

const AssignmentsRouteWithChildren = AssignmentsRoute._addFileChildren(
  AssignmentsRouteChildren,
)

interface GalleryRouteChildren {
  GalleryPostIdRoute: typeof GalleryPostIdRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GalleryPostIdRoute: GalleryPostIdRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

interface InquiriesRouteChildren {
  InquiriesThreadIdRoute: typeof InquiriesThreadIdRoute
}

const InquiriesRouteChildren: InquiriesRouteChildren = {
  InquiriesThreadIdRoute: InquiriesThreadIdRoute,
}

const InquiriesRouteWithChildren = InquiriesRoute._addFileChildren(
  InquiriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssignmentsRoute: AssignmentsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRouteWithChildren,
  InquiriesRoute: InquiriesRouteWithChildren,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  NoticesRoute: NoticesRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
  PostPostIdRoute: PostPostIdRoute,
  PostNewRoute: PostNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
